server {
    listen 8080;
    server_name _;

    root /var/www/apks;

    location / {
        try_files $uri @upstream;
    }

    location @upstream {
        proxy_pass https://packages.wolfi.dev;
        proxy_set_header Host packages.wolfi.dev;
        proxy_ssl_server_name on;
    }
}

